/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse2004 } from '../models';
/**
 * UserAuthenticatedUserApi - axios parameter creator
 * @export
 */
export const UserAuthenticatedUserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get currently authenticated user settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthenticatedUserSettings: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/auth/settings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserAuthenticatedUserApi - functional programming interface
 * @export
 */
export const UserAuthenticatedUserApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get currently authenticated user settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuthenticatedUserSettings(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2004>>> {
            const localVarAxiosArgs = await UserAuthenticatedUserApiAxiosParamCreator(configuration).getAuthenticatedUserSettings(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UserAuthenticatedUserApi - factory interface
 * @export
 */
export const UserAuthenticatedUserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get currently authenticated user settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuthenticatedUserSettings(options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2004>> {
            return UserAuthenticatedUserApiFp(configuration).getAuthenticatedUserSettings(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserAuthenticatedUserApi - object-oriented interface
 * @export
 * @class UserAuthenticatedUserApi
 * @extends {BaseAPI}
 */
export class UserAuthenticatedUserApi extends BaseAPI {
    /**
     * 
     * @summary Get currently authenticated user settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAuthenticatedUserApi
     */
    public async getAuthenticatedUserSettings(options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2004>> {
        return UserAuthenticatedUserApiFp(this.configuration).getAuthenticatedUserSettings(options).then((request) => request(this.axios, this.basePath));
    }
}
