/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse20027 } from '../models';
/**
 * ArtworkRandomApi - axios parameter creator
 * @export
 */
export const ArtworkRandomApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Roll a dice and get a random artwork
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRandomArtwork: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/artworks/random`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ArtworkRandomApi - functional programming interface
 * @export
 */
export const ArtworkRandomApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Roll a dice and get a random artwork
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRandomArtwork(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20027>>> {
            const localVarAxiosArgs = await ArtworkRandomApiAxiosParamCreator(configuration).getRandomArtwork(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ArtworkRandomApi - factory interface
 * @export
 */
export const ArtworkRandomApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Roll a dice and get a random artwork
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRandomArtwork(options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20027>> {
            return ArtworkRandomApiFp(configuration).getRandomArtwork(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ArtworkRandomApi - object-oriented interface
 * @export
 * @class ArtworkRandomApi
 * @extends {BaseAPI}
 */
export class ArtworkRandomApi extends BaseAPI {
    /**
     * 
     * @summary Roll a dice and get a random artwork
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArtworkRandomApi
     */
    public async getRandomArtwork(options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20027>> {
        return ArtworkRandomApiFp(this.configuration).getRandomArtwork(options).then((request) => request(this.axios, this.basePath));
    }
}
