/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse20042 } from '../models';
import { InlineResponse20043 } from '../models';
import { ProRegisterBody } from '../models';
/**
 * ProApi - axios parameter creator
 * @export
 */
export const ProApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get PRO status by user login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProStatus: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pro/check`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get PRO status by user login
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProStatusByUserId: async (userId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling getProStatusByUserId.');
            }
            const localVarPath = `/pro/check/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Subscribe to pro version
         * @param {ProRegisterBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerProVersion: async (body?: ProRegisterBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pro/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProApi - functional programming interface
 * @export
 */
export const ProApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get PRO status by user login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProStatus(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20043>>> {
            const localVarAxiosArgs = await ProApiAxiosParamCreator(configuration).getProStatus(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get PRO status by user login
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProStatusByUserId(userId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20043>>> {
            const localVarAxiosArgs = await ProApiAxiosParamCreator(configuration).getProStatusByUserId(userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Subscribe to pro version
         * @param {ProRegisterBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerProVersion(body?: ProRegisterBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20042>>> {
            const localVarAxiosArgs = await ProApiAxiosParamCreator(configuration).registerProVersion(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProApi - factory interface
 * @export
 */
export const ProApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get PRO status by user login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProStatus(options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20043>> {
            return ProApiFp(configuration).getProStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get PRO status by user login
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProStatusByUserId(userId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20043>> {
            return ProApiFp(configuration).getProStatusByUserId(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Subscribe to pro version
         * @param {ProRegisterBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerProVersion(body?: ProRegisterBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20042>> {
            return ProApiFp(configuration).registerProVersion(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProApi - object-oriented interface
 * @export
 * @class ProApi
 * @extends {BaseAPI}
 */
export class ProApi extends BaseAPI {
    /**
     * 
     * @summary Get PRO status by user login
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProApi
     */
    public async getProStatus(options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20043>> {
        return ProApiFp(this.configuration).getProStatus(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get PRO status by user login
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProApi
     */
    public async getProStatusByUserId(userId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20043>> {
        return ProApiFp(this.configuration).getProStatusByUserId(userId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Subscribe to pro version
     * @param {ProRegisterBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProApi
     */
    public async registerProVersion(body?: ProRegisterBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20042>> {
        return ProApiFp(this.configuration).registerProVersion(body, options).then((request) => request(this.axios, this.basePath));
    }
}
