/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlbumHasArtworksModel } from './album-has-artworks-model';
import { AlbumHasArtworksModelArtworkAlbumHasWorks } from './album-has-artworks-model-artwork-album-has-works';
import { AlbumLiteModel } from './album-lite-model';
import { AlbumLiteModelCount } from './album-lite-model-count';
import { UserLiteModel } from './user-lite-model';
/**
 * 
 * @export
 * @interface AlbumModel
 */
export interface AlbumModel extends AlbumLiteModel {
    /**
     * 
     * @type {Array<AlbumHasArtworksModelArtworkAlbumHasWorks>}
     * @memberof AlbumModel
     */
    artworkAlbumHasWorks?: Array<AlbumHasArtworksModelArtworkAlbumHasWorks>;
    /**
     * 
     * @type {UserLiteModel}
     * @memberof AlbumModel
     */
    users?: UserLiteModel;
    /**
     * 
     * @type {boolean}
     * @memberof AlbumModel
     */
    isCanAddMore?: boolean;
}


