/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostTypes } from './post-types';
/**
 * 
 * @export
 * @interface AlbumsAddworkBody
 */
export interface AlbumsAddworkBody {
    /**
     * 
     * @type {number}
     * @memberof AlbumsAddworkBody
     */
    albumId: number;
    /**
     * 
     * @type {PostTypes}
     * @memberof AlbumsAddworkBody
     */
    type?: PostTypes;
    /**
     * 
     * @type {Array<number>}
     * @memberof AlbumsAddworkBody
     */
    workIds: Array<number>;
}
