/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostTypes } from './post-types';
/**
 * 
 * @export
 * @interface AlbumsCreateBody
 */
export interface AlbumsCreateBody {
    /**
     * 
     * @type {string}
     * @memberof AlbumsCreateBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AlbumsCreateBody
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof AlbumsCreateBody
     */
    isPublic: AlbumsCreateBodyIsPublicEnum;
    /**
     * 
     * @type {PostTypes}
     * @memberof AlbumsCreateBody
     */
    type: PostTypes;
}

/**
    * @export
    * @enum {string}
    */
export enum AlbumsCreateBodyIsPublicEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

