/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArtworkAssetsModel } from './artwork-assets-model';
import { ArtworkHasTagsModel } from './artwork-has-tags-model';
import { ArtworkLiteModel } from './artwork-lite-model';
import { ArtworkModelCount } from './artwork-model-count';
import { UserLiteModel } from './user-lite-model';
/**
 * 
 * @export
 * @interface ArtworkModel
 */
export interface ArtworkModel extends ArtworkLiteModel {
    /**
     * 
     * @type {string}
     * @memberof ArtworkModel
     */
    createdAt?: string;
    /**
     * 
     * @type {ArtworkHasTagsModel}
     * @memberof ArtworkModel
     */
    artworkHasTags?: ArtworkHasTagsModel;
    /**
     * 
     * @type {ArtworkModelCount}
     * @memberof ArtworkModel
     */
    count?: ArtworkModelCount;
    /**
     * 
     * @type {boolean}
     * @memberof ArtworkModel
     */
    liked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ArtworkModel
     */
    saved?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ArtworkModel
     */
    inAlbum?: boolean;
}


