/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ArtworkModelCount
 */
export interface ArtworkModelCount {
    /**
     * 
     * @type {number}
     * @memberof ArtworkModelCount
     */
    artworkAssets?: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkModelCount
     */
    artworkComments?: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkModelCount
     */
    artworkLikes?: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkModelCount
     */
    collectionHasArtworks?: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkModelCount
     */
    feeds?: number;
}
