/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CounterModelData } from './counter-model-data';
/**
 * 
 * @export
 * @interface CounterModel
 */
export interface CounterModel {
    /**
     * 
     * @type {boolean}
     * @memberof CounterModel
     */
    success?: boolean;
    /**
     * 
     * @type {CounterModelData}
     * @memberof CounterModel
     */
    data?: CounterModelData;
}
