/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FeedsCreateBody
 */
export interface FeedsCreateBody {
    /**
     * 
     * @type {number}
     * @memberof FeedsCreateBody
     */
    text: number;
    /**
     * 
     * @type {string}
     * @memberof FeedsCreateBody
     */
    visibility: FeedsCreateBodyVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof FeedsCreateBody
     */
    whoCanReply: FeedsCreateBodyWhoCanReplyEnum;
    /**
     * 
     * @type {number}
     * @memberof FeedsCreateBody
     */
    workId?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedsCreateBody
     */
    feedId?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum FeedsCreateBodyVisibilityEnum {
    Public = 'public',
    Followers = 'followers'
}
/**
    * @export
    * @enum {string}
    */
export enum FeedsCreateBodyWhoCanReplyEnum {
    Public = 'public',
    Followers = 'followers'
}

