/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FeedLiteModel
 */
export interface FeedLiteModel {
    /**
     * 
     * @type {number}
     * @memberof FeedLiteModel
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedLiteModel
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedLiteModel
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedLiteModel
     */
    visibility?: FeedLiteModelVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof FeedLiteModel
     */
    whoCanReply?: FeedLiteModelWhoCanReplyEnum;
    /**
     * 
     * @type {number}
     * @memberof FeedLiteModel
     */
    workId?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedLiteModel
     */
    feedId?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedLiteModel
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedLiteModel
     */
    updatedAt?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum FeedLiteModelVisibilityEnum {
    Public = 'public',
    Followers = 'followers'
}
/**
    * @export
    * @enum {string}
    */
export enum FeedLiteModelWhoCanReplyEnum {
    Public = 'public',
    Followers = 'followers'
}

