/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20046Data } from './inline-response20046-data';
/**
 * 
 * @export
 * @interface InlineResponse20046
 */
export interface InlineResponse20046 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20046
     */
    success?: boolean;
    /**
     * 
     * @type {InlineResponse20046Data}
     * @memberof InlineResponse20046
     */
    data?: InlineResponse20046Data;
}
