/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20055DataReport
 */
export interface InlineResponse20055DataReport {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20055DataReport
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20055DataReport
     */
    status?: string;
}
