/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArtworkLiteModel } from './artwork-lite-model';
import { PaginationModel } from './pagination-model';
/**
 * 
 * @export
 * @interface InlineResponse20025Data
 */
export interface InlineResponse20025Data {
    /**
     * 
     * @type {Array<ArtworkLiteModel>}
     * @memberof InlineResponse20025Data
     */
    redraws?: Array<ArtworkLiteModel>;
    /**
     * 
     * @type {PaginationModel}
     * @memberof InlineResponse20025Data
     */
    pagination?: PaginationModel;
}
