/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20028DataCount } from './inline-response20028-data-count';
/**
 * 
 * @export
 * @interface InlineResponse20028DataTags
 */
export interface InlineResponse20028DataTags {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20028DataTags
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20028DataTags
     */
    tag?: string;
    /**
     * 
     * @type {InlineResponse20028DataCount}
     * @memberof InlineResponse20028DataTags
     */
    count?: InlineResponse20028DataCount;
}
