/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20035DataUserLiked } from './inline-response20035-data-user-liked';
/**
 * 
 * @export
 * @interface InlineResponse20035DataNotifications
 */
export interface InlineResponse20035DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20035DataNotifications
     */
    workId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20035DataNotifications
     */
    isRead?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20035DataNotifications
     */
    driver?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20035DataNotifications
     */
    bucket?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20035DataNotifications
     */
    b2FileId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20035DataNotifications
     */
    filename?: string;
    /**
     * 
     * @type {Array<InlineResponse20035DataUserLiked>}
     * @memberof InlineResponse20035DataNotifications
     */
    userLiked?: Array<InlineResponse20035DataUserLiked>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20035DataNotifications
     */
    totalLiked?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20035DataNotifications
     */
    restTotalLiked?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20035DataNotifications
     */
    createdAt?: string;
}
