/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20037DataFollowerDetail } from './inline-response20037-data-follower-detail';
/**
 * 
 * @export
 * @interface InlineResponse20038DataNotifications
 */
export interface InlineResponse20038DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20038DataNotifications
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20038DataNotifications
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20038DataNotifications
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20038DataNotifications
     */
    isRead?: boolean;
    /**
     * 
     * @type {Array<InlineResponse20037DataFollowerDetail>}
     * @memberof InlineResponse20038DataNotifications
     */
    users?: Array<InlineResponse20037DataFollowerDetail>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20038DataNotifications
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20038DataNotifications
     */
    restTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20038DataNotifications
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20038DataNotifications
     */
    type?: InlineResponse20038DataNotificationsTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse20038DataNotificationsTypeEnum {
    Like = 'like',
    Comment = 'comment'
}

