/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20056Data
 */
export interface InlineResponse20056Data {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20056Data
     */
    isPro?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20056Data
     */
    until?: string;
}
