/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20043DataArtworksArtworkAssets } from './inline-response20043-data-artworks-artwork-assets';
/**
 * 
 * @export
 * @interface InlineResponse20044DataArtworks
 */
export interface InlineResponse20044DataArtworks {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20044DataArtworks
     */
    id?: number;
    /**
     * 
     * @type {InlineResponse20043DataArtworksArtworkAssets}
     * @memberof InlineResponse20044DataArtworks
     */
    assets?: InlineResponse20043DataArtworksArtworkAssets;
}
