/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20035DataArtworks } from './inline-response20035-data-artworks';
import { InlineResponse20035DataUsers } from './inline-response20035-data-users';
/**
 * 
 * @export
 * @interface InlineResponse20035DataNotifications
 */
export interface InlineResponse20035DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20035DataNotifications
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20035DataNotifications
     */
    workId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20035DataNotifications
     */
    comment?: string;
    /**
     * 
     * @type {InlineResponse20035DataUsers}
     * @memberof InlineResponse20035DataNotifications
     */
    users?: InlineResponse20035DataUsers;
    /**
     * 
     * @type {InlineResponse20035DataArtworks}
     * @memberof InlineResponse20035DataNotifications
     */
    artworks?: InlineResponse20035DataArtworks;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20035DataNotifications
     */
    createdAt?: string;
}
