/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20050Data
 */
export interface InlineResponse20050Data {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20050Data
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20050Data
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20050Data
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20050Data
     */
    paymentType?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20050Data
     */
    orderData?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20050Data
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20050Data
     */
    until?: string;
}
