/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20047DataFollowerDetail } from './inline-response20047-data-follower-detail';
/**
 * 
 * @export
 * @interface InlineResponse20047DataNotifications
 */
export interface InlineResponse20047DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20047DataNotifications
     */
    isRead?: number;
    /**
     * 
     * @type {Array<InlineResponse20047DataFollowerDetail>}
     * @memberof InlineResponse20047DataNotifications
     */
    followerDetail?: Array<InlineResponse20047DataFollowerDetail>;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20047DataNotifications
     */
    createdAt?: string;
}
