/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2005Data } from './inline-response2005-data';
import { SuccessMessageModel } from './success-message-model';
/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 extends SuccessMessageModel {
    /**
     * 
     * @type {InlineResponse2005Data}
     * @memberof InlineResponse2005
     */
    data?: InlineResponse2005Data;
}
