/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArtworkAssetsModel } from './artwork-assets-model';
import { InlineResponse20048DataArtworkShareInfo } from './inline-response20048-data-artwork-share-info';
import { InlineResponse20048DataCount } from './inline-response20048-data-count';
import { InlineResponse20048DataRedrawedArtworkInfo } from './inline-response20048-data-redrawed-artwork-info';
import { UserLiteModel } from './user-lite-model';
/**
 * 
 * @export
 * @interface InlineResponse20048DataFeeds
 */
export interface InlineResponse20048DataFeeds {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20048DataFeeds
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20048DataFeeds
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20048DataFeeds
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20048DataFeeds
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20048DataFeeds
     */
    isExplicit?: InlineResponse20048DataFeedsIsExplicitEnum;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20048DataFeeds
     */
    scheduledPost?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20048DataFeeds
     */
    redrawOf?: number;
    /**
     * 
     * @type {UserLiteModel}
     * @memberof InlineResponse20048DataFeeds
     */
    users?: UserLiteModel;
    /**
     * 
     * @type {InlineResponse20048DataArtworkShareInfo}
     * @memberof InlineResponse20048DataFeeds
     */
    artworkShareInfo?: InlineResponse20048DataArtworkShareInfo;
    /**
     * 
     * @type {InlineResponse20048DataRedrawedArtworkInfo}
     * @memberof InlineResponse20048DataFeeds
     */
    redrawedArtworkInfo?: InlineResponse20048DataRedrawedArtworkInfo;
    /**
     * 
     * @type {Array<ArtworkAssetsModel>}
     * @memberof InlineResponse20048DataFeeds
     */
    artworkAssets?: Array<ArtworkAssetsModel>;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20048DataFeeds
     */
    liked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20048DataFeeds
     */
    saved?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20048DataFeeds
     */
    visibility?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20048DataFeeds
     */
    whoCanReply?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20048DataFeeds
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20048DataFeeds
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20048DataFeeds
     */
    type?: InlineResponse20048DataFeedsTypeEnum;
    /**
     * 
     * @type {InlineResponse20048DataCount}
     * @memberof InlineResponse20048DataFeeds
     */
    count?: InlineResponse20048DataCount;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse20048DataFeedsIsExplicitEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
    * @export
    * @enum {string}
    */
export enum InlineResponse20048DataFeedsTypeEnum {
    Artwork = 'artwork',
    Feed = 'feed'
}

