/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20035DataTags
 */
export interface InlineResponse20035DataTags {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20035DataTags
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20035DataTags
     */
    tag?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20035DataTags
     */
    count?: number;
}
