/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20047Data } from './inline-response20047-data';
import { SuccessMessageModel } from './success-message-model';
/**
 * 
 * @export
 * @interface InlineResponse20047
 */
export interface InlineResponse20047 extends SuccessMessageModel {
    /**
     * 
     * @type {InlineResponse20047Data}
     * @memberof InlineResponse20047
     */
    data?: InlineResponse20047Data;
}
