/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20045DataNotifications } from './inline-response20045-data-notifications';
import { PaginationModel } from './pagination-model';
/**
 * 
 * @export
 * @interface InlineResponse20045Data
 */
export interface InlineResponse20045Data {
    /**
     * 
     * @type {InlineResponse20045DataNotifications}
     * @memberof InlineResponse20045Data
     */
    notifications?: InlineResponse20045DataNotifications;
    /**
     * 
     * @type {PaginationModel}
     * @memberof InlineResponse20045Data
     */
    pagination?: PaginationModel;
}
