/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20029DataCount } from './inline-response20029-data-count';
/**
 * 
 * @export
 * @interface InlineResponse20029DataTags
 */
export interface InlineResponse20029DataTags {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20029DataTags
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20029DataTags
     */
    tag?: string;
    /**
     * 
     * @type {InlineResponse20029DataCount}
     * @memberof InlineResponse20029DataTags
     */
    count?: InlineResponse20029DataCount;
}
