/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20019Data } from './inline-response20019-data';
/**
 * 
 * @export
 * @interface InlineResponse20028
 */
export interface InlineResponse20028 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20028
     */
    success?: boolean;
    /**
     * 
     * @type {InlineResponse20019Data}
     * @memberof InlineResponse20028
     */
    data?: InlineResponse20019Data;
}
