/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20049Data } from './inline-response20049-data';
import { SuccessMessageModel } from './success-message-model';
/**
 * 
 * @export
 * @interface InlineResponse20049
 */
export interface InlineResponse20049 extends SuccessMessageModel {
    /**
     * 
     * @type {InlineResponse20049Data}
     * @memberof InlineResponse20049
     */
    data?: InlineResponse20049Data;
}
