/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserLiteModel } from './user-lite-model';
/**
 * 
 * @export
 * @interface InlineResponse20038DataArtworkShareInfo
 */
export interface InlineResponse20038DataArtworkShareInfo {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20038DataArtworkShareInfo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20038DataArtworkShareInfo
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20038DataArtworkShareInfo
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20038DataArtworkShareInfo
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20038DataArtworkShareInfo
     */
    isExplicit?: InlineResponse20038DataArtworkShareInfoIsExplicitEnum;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20038DataArtworkShareInfo
     */
    scheduledPost?: string;
    /**
     * 
     * @type {UserLiteModel}
     * @memberof InlineResponse20038DataArtworkShareInfo
     */
    users?: UserLiteModel;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse20038DataArtworkShareInfoIsExplicitEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

