/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20018DataUsers } from './inline-response20018-data-users';
import { PaginationModel } from './pagination-model';
/**
 * 
 * @export
 * @interface InlineResponse20018Data
 */
export interface InlineResponse20018Data {
    /**
     * 
     * @type {Array<InlineResponse20018DataUsers>}
     * @memberof InlineResponse20018Data
     */
    users?: Array<InlineResponse20018DataUsers>;
    /**
     * 
     * @type {PaginationModel}
     * @memberof InlineResponse20018Data
     */
    pagination?: PaginationModel;
}
