/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20032DataCount } from './inline-response20032-data-count';
/**
 * 
 * @export
 * @interface InlineResponse20032DataTags
 */
export interface InlineResponse20032DataTags {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032DataTags
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20032DataTags
     */
    tag?: string;
    /**
     * 
     * @type {InlineResponse20032DataCount}
     * @memberof InlineResponse20032DataTags
     */
    count?: InlineResponse20032DataCount;
}
