/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2016Data } from './inline-response2016-data';
/**
 * 
 * @export
 * @interface InlineResponse2016
 */
export interface InlineResponse2016 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2016
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2016
     */
    message?: string;
    /**
     * 
     * @type {InlineResponse2016Data}
     * @memberof InlineResponse2016
     */
    data?: InlineResponse2016Data;
}
