/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlbumModel } from './album-model';
import { PaginationModel } from './pagination-model';
/**
 * 
 * @export
 * @interface InlineResponse20019Data
 */
export interface InlineResponse20019Data {
    /**
     * 
     * @type {Array<AlbumModel>}
     * @memberof InlineResponse20019Data
     */
    albums?: Array<AlbumModel>;
    /**
     * 
     * @type {PaginationModel}
     * @memberof InlineResponse20019Data
     */
    pagination?: PaginationModel;
}
