/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20016DataUsers } from './inline-response20016-data-users';
import { PaginationModel } from './pagination-model';
/**
 * 
 * @export
 * @interface InlineResponse20016Data
 */
export interface InlineResponse20016Data {
    /**
     * 
     * @type {Array<InlineResponse20016DataUsers>}
     * @memberof InlineResponse20016Data
     */
    users?: Array<InlineResponse20016DataUsers>;
    /**
     * 
     * @type {PaginationModel}
     * @memberof InlineResponse20016Data
     */
    pagination?: PaginationModel;
}
