/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20026Data } from './inline-response20026-data';
import { SuccessMessageModel } from './success-message-model';
/**
 * 
 * @export
 * @interface InlineResponse20026
 */
export interface InlineResponse20026 extends SuccessMessageModel {
    /**
     * 
     * @type {InlineResponse20026Data}
     * @memberof InlineResponse20026
     */
    data?: InlineResponse20026Data;
}
