/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LatestTradesModel } from './latest-trades-model';
/**
 * 
 * @export
 * @interface InlineResponse20037DataLatestTrades
 */
export interface InlineResponse20037DataLatestTrades {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20037DataLatestTrades
     */
    id?: number;
    /**
     * 
     * @type {LatestTradesModel}
     * @memberof InlineResponse20037DataLatestTrades
     */
    host?: LatestTradesModel;
    /**
     * 
     * @type {LatestTradesModel}
     * @memberof InlineResponse20037DataLatestTrades
     */
    participant?: LatestTradesModel;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20037DataLatestTrades
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20037DataLatestTrades
     */
    updatedAt?: string;
}
