/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20032DataUserLiked } from './inline-response20032-data-user-liked';
import { InlineResponse20035DataArtworks } from './inline-response20035-data-artworks';
/**
 * 
 * @export
 * @interface InlineResponse20036DataNotifications
 */
export interface InlineResponse20036DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20036DataNotifications
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20036DataNotifications
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20036DataNotifications
     */
    commentId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20036DataNotifications
     */
    comment?: string;
    /**
     * 
     * @type {Array<InlineResponse20032DataUserLiked>}
     * @memberof InlineResponse20036DataNotifications
     */
    userReplied?: Array<InlineResponse20032DataUserLiked>;
    /**
     * 
     * @type {InlineResponse20035DataArtworks}
     * @memberof InlineResponse20036DataNotifications
     */
    artworks?: InlineResponse20035DataArtworks;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20036DataNotifications
     */
    totalLiked?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20036DataNotifications
     */
    restTotalLiked?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20036DataNotifications
     */
    createdAt?: string;
}
