/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserLiteModel } from './user-lite-model';
/**
 * 
 * @export
 * @interface InlineResponse20045DataArtworkShareInfo
 */
export interface InlineResponse20045DataArtworkShareInfo {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20045DataArtworkShareInfo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20045DataArtworkShareInfo
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20045DataArtworkShareInfo
     */
    isExplicit?: InlineResponse20045DataArtworkShareInfoIsExplicitEnum;
    /**
     * 
     * @type {UserLiteModel}
     * @memberof InlineResponse20045DataArtworkShareInfo
     */
    users?: UserLiteModel;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse20045DataArtworkShareInfoIsExplicitEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

