/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20048DataNotifications } from './inline-response20048-data-notifications';
import { PaginationModel } from './pagination-model';
/**
 * 
 * @export
 * @interface InlineResponse20048Data
 */
export interface InlineResponse20048Data {
    /**
     * 
     * @type {InlineResponse20048DataNotifications}
     * @memberof InlineResponse20048Data
     */
    notifications?: InlineResponse20048DataNotifications;
    /**
     * 
     * @type {PaginationModel}
     * @memberof InlineResponse20048Data
     */
    pagination?: PaginationModel;
}
