/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20038DataFollowerDetail } from './inline-response20038-data-follower-detail';
/**
 * 
 * @export
 * @interface InlineResponse20039DataNotifications
 */
export interface InlineResponse20039DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20039DataNotifications
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataNotifications
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataNotifications
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20039DataNotifications
     */
    isRead?: boolean;
    /**
     * 
     * @type {Array<InlineResponse20038DataFollowerDetail>}
     * @memberof InlineResponse20039DataNotifications
     */
    users?: Array<InlineResponse20038DataFollowerDetail>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20039DataNotifications
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20039DataNotifications
     */
    restTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataNotifications
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataNotifications
     */
    type?: InlineResponse20039DataNotificationsTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse20039DataNotificationsTypeEnum {
    Like = 'like',
    Comment = 'comment'
}

