/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20040DataNotifications } from './inline-response20040-data-notifications';
import { PaginationModel } from './pagination-model';
/**
 * 
 * @export
 * @interface InlineResponse20040Data
 */
export interface InlineResponse20040Data {
    /**
     * 
     * @type {Array<InlineResponse20040DataNotifications>}
     * @memberof InlineResponse20040Data
     */
    notifications?: Array<InlineResponse20040DataNotifications>;
    /**
     * 
     * @type {PaginationModel}
     * @memberof InlineResponse20040Data
     */
    pagination?: PaginationModel;
}
