/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20037Data } from './inline-response20037-data';
/**
 * 
 * @export
 * @interface InlineResponse20037
 */
export interface InlineResponse20037 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20037
     */
    success?: boolean;
    /**
     * 
     * @type {InlineResponse20037Data}
     * @memberof InlineResponse20037
     */
    data?: InlineResponse20037Data;
}
