/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20041DataArtworks } from './inline-response20041-data-artworks';
import { InlineResponse20041DataUserLiked } from './inline-response20041-data-user-liked';
/**
 * 
 * @export
 * @interface InlineResponse20041DataNotifications
 */
export interface InlineResponse20041DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20041DataNotifications
     */
    commentId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20041DataNotifications
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20041DataNotifications
     */
    isRead?: number;
    /**
     * 
     * @type {Array<InlineResponse20041DataUserLiked>}
     * @memberof InlineResponse20041DataNotifications
     */
    userLiked?: Array<InlineResponse20041DataUserLiked>;
    /**
     * 
     * @type {InlineResponse20041DataArtworks}
     * @memberof InlineResponse20041DataNotifications
     */
    artworks?: InlineResponse20041DataArtworks;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20041DataNotifications
     */
    totalLiked?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20041DataNotifications
     */
    restTotalLiked?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20041DataNotifications
     */
    createdAt?: string;
}
