/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20043FeedCount } from './inline-response20043-feed-count';
import { UserLiteModel } from './user-lite-model';
/**
 * 
 * @export
 * @interface InlineResponse20043Feed
 */
export interface InlineResponse20043Feed {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    text?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    visibility?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    whoCanReply?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    workId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    feedId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    createdAt?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    updatedAt?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    feedHasFiles?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    artworks?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043Feed
     */
    feeds?: number;
    /**
     * 
     * @type {UserLiteModel}
     * @memberof InlineResponse20043Feed
     */
    users?: UserLiteModel;
    /**
     * 
     * @type {InlineResponse20043FeedCount}
     * @memberof InlineResponse20043Feed
     */
    count?: InlineResponse20043FeedCount;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20043Feed
     */
    liked?: boolean;
}
