/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20027DataTags } from './inline-response20027-data-tags';
/**
 * 
 * @export
 * @interface InlineResponse20027Data
 */
export interface InlineResponse20027Data {
    /**
     * 
     * @type {Array<InlineResponse20027DataTags>}
     * @memberof InlineResponse20027Data
     */
    tags?: Array<InlineResponse20027DataTags>;
}
