/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20034DataTags } from './inline-response20034-data-tags';
/**
 * 
 * @export
 * @interface InlineResponse20034Data
 */
export interface InlineResponse20034Data {
    /**
     * 
     * @type {Array<InlineResponse20034DataTags>}
     * @memberof InlineResponse20034Data
     */
    tags?: Array<InlineResponse20034DataTags>;
}
