/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArtworksUnlikeBody } from './artworks-unlike-body';
/**
 * 
 * @export
 * @interface InlineResponse20036
 */
export interface InlineResponse20036 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20036
     */
    success?: boolean;
    /**
     * 
     * @type {ArtworksUnlikeBody}
     * @memberof InlineResponse20036
     */
    data?: ArtworksUnlikeBody;
}
