/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20018Data
 */
export interface InlineResponse20018Data {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20018Data
     */
    albumId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20018Data
     */
    workId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20018Data
     */
    createdAt?: string;
}
