/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20042Data } from './inline-response20042-data';
/**
 * 
 * @export
 * @interface InlineResponse20042
 */
export interface InlineResponse20042 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20042
     */
    success?: boolean;
    /**
     * 
     * @type {InlineResponse20042Data}
     * @memberof InlineResponse20042
     */
    data?: InlineResponse20042Data;
}
