/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20033DataArtworks } from './inline-response20033-data-artworks';
import { InlineResponse20033DataUsers } from './inline-response20033-data-users';
/**
 * 
 * @export
 * @interface InlineResponse20033DataNotifications
 */
export interface InlineResponse20033DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20033DataNotifications
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20033DataNotifications
     */
    workId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20033DataNotifications
     */
    comment?: string;
    /**
     * 
     * @type {InlineResponse20033DataUsers}
     * @memberof InlineResponse20033DataNotifications
     */
    users?: InlineResponse20033DataUsers;
    /**
     * 
     * @type {InlineResponse20033DataArtworks}
     * @memberof InlineResponse20033DataNotifications
     */
    artworks?: InlineResponse20033DataArtworks;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20033DataNotifications
     */
    createdAt?: string;
}
