/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20049FeedCount
 */
export interface InlineResponse20049FeedCount {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20049FeedCount
     */
    feedComments?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20049FeedCount
     */
    feedLikes?: number;
}
