/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20032DataTags } from './inline-response20032-data-tags';
/**
 * 
 * @export
 * @interface InlineResponse20032Data
 */
export interface InlineResponse20032Data {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032Data
     */
    count?: number;
    /**
     * 
     * @type {Array<InlineResponse20032DataTags>}
     * @memberof InlineResponse20032Data
     */
    tags?: Array<InlineResponse20032DataTags>;
}
