/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PaginationModelFirstLast
 */
export interface PaginationModelFirstLast {
    /**
     * 
     * @type {number}
     * @memberof PaginationModelFirstLast
     */
    firstPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationModelFirstLast
     */
    lastPage?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginationModelFirstLast
     */
    firstPageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginationModelFirstLast
     */
    lastPageUrl?: string;
}
