/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReplyModelCount } from './reply-model-count';
/**
 * 
 * @export
 * @interface ReplyModel
 */
export interface ReplyModel {
    /**
     * 
     * @type {number}
     * @memberof ReplyModel
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ReplyModel
     */
    commentId?: number;
    /**
     * 
     * @type {number}
     * @memberof ReplyModel
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof ReplyModel
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof ReplyModel
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ReplyModel
     */
    updatedAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReplyModel
     */
    liked?: boolean;
    /**
     * 
     * @type {ReplyModelCount}
     * @memberof ReplyModel
     */
    count?: ReplyModelCount;
}
