/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateInfoBody
 */
export interface UpdateInfoBody {
    /**
     * 
     * @type {number}
     * @memberof UpdateInfoBody
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateInfoBody
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateInfoBody
     */
    gender?: UpdateInfoBodyGenderEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateInfoBody
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateInfoBody
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateInfoBody
     */
    penName?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateInfoBodyGenderEnum {
    M = 'm',
    F = 'f'
}

