/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateSocialBody
 */
export interface UpdateSocialBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateSocialBody
     */
    facebook?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSocialBody
     */
    instagram?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSocialBody
     */
    patreon?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSocialBody
     */
    twitter?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSocialBody
     */
    youtube?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSocialBody
     */
    twitch?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSocialBody
     */
    discord?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSocialBody
     */
    gumroad?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSocialBody
     */
    picarto?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSocialBody
     */
    personalWebsite?: string;
}
