/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserLiteModel } from './user-lite-model';
/**
 * 
 * @export
 * @interface UserModel
 */
export interface UserModel extends UserLiteModel {
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    gender?: UserModelGenderEnum;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    coverDriver?: string;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    coverBucket?: string;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    coverB2FileId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    coverFilename?: string;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    createdAt?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum UserModelGenderEnum {
    M = 'm',
    F = 'f'
}

