/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WorkRemoveBody
 */
export interface WorkRemoveBody {
    /**
     * 
     * @type {number}
     * @memberof WorkRemoveBody
     */
    albumId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof WorkRemoveBody
     */
    workIds: Array<number>;
}
