/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlbumHasArtworksModelArtworkAlbumHasWorks } from './album-has-artworks-model-artwork-album-has-works';
/**
 * 
 * @export
 * @interface AlbumHasArtworksModel
 */
export interface AlbumHasArtworksModel {
    /**
     * 
     * @type {Array<AlbumHasArtworksModelArtworkAlbumHasWorks>}
     * @memberof AlbumHasArtworksModel
     */
    artworkAlbumHasWorks?: Array<AlbumHasArtworksModelArtworkAlbumHasWorks>;
}
