/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CollectionsCreateBody
 */
export interface CollectionsCreateBody {
    /**
     * 
     * @type {string}
     * @memberof CollectionsCreateBody
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCreateBody
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionsCreateBody
     */
    isPublic?: CollectionsCreateBodyIsPublicEnum;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCreateBody
     */
    type?: CollectionsCreateBodyTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CollectionsCreateBodyIsPublicEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
    * @export
    * @enum {string}
    */
export enum CollectionsCreateBodyTypeEnum {
    Artwork = 'artwork',
    Comic = 'comic',
    Tutorial = 'tutorial'
}

