/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CollectionHasArtworksModel } from './collection-has-artworks-model';
import { CollectionModelCount } from './collection-model-count';
import { UserLiteModel } from './user-lite-model';
/**
 * 
 * @export
 * @interface CollectionModel
 */
export interface CollectionModel {
    /**
     * 
     * @type {number}
     * @memberof CollectionModel
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CollectionModel
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionModel
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionModel
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionModel
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionModel
     */
    isPublic?: number;
    /**
     * 
     * @type {number}
     * @memberof CollectionModel
     */
    isEditable?: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionModel
     */
    createdAt?: string;
    /**
     * 
     * @type {CollectionModelCount}
     * @memberof CollectionModel
     */
    count?: CollectionModelCount;
    /**
     * 
     * @type {Array<CollectionHasArtworksModel>}
     * @memberof CollectionModel
     */
    collectionHasArtworks?: Array<CollectionHasArtworksModel>;
    /**
     * 
     * @type {UserLiteModel}
     * @memberof CollectionModel
     */
    users?: UserLiteModel;
}
