/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20028DataUserLiked } from './inline-response20028-data-user-liked';
import { InlineResponse20031DataArtworks } from './inline-response20031-data-artworks';
/**
 * 
 * @export
 * @interface InlineResponse20032DataNotifications
 */
export interface InlineResponse20032DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032DataNotifications
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20032DataNotifications
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032DataNotifications
     */
    commentId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20032DataNotifications
     */
    comment?: string;
    /**
     * 
     * @type {Array<InlineResponse20028DataUserLiked>}
     * @memberof InlineResponse20032DataNotifications
     */
    userReplied?: Array<InlineResponse20028DataUserLiked>;
    /**
     * 
     * @type {InlineResponse20031DataArtworks}
     * @memberof InlineResponse20032DataNotifications
     */
    artworks?: InlineResponse20031DataArtworks;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032DataNotifications
     */
    totalLiked?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032DataNotifications
     */
    restTotalLiked?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20032DataNotifications
     */
    createdAt?: string;
}
