/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20045Data } from './inline-response20045-data';
/**
 * 
 * @export
 * @interface InlineResponse20045
 */
export interface InlineResponse20045 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20045
     */
    success?: boolean;
    /**
     * 
     * @type {InlineResponse20045Data}
     * @memberof InlineResponse20045
     */
    data?: InlineResponse20045Data;
}
