/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArtworkAssetsModel } from './artwork-assets-model';
import { InlineResponse20039DataArtworkShareInfo } from './inline-response20039-data-artwork-share-info';
import { InlineResponse20039DataCount } from './inline-response20039-data-count';
import { UserLiteModel } from './user-lite-model';
/**
 * 
 * @export
 * @interface InlineResponse20039DataFeeds
 */
export interface InlineResponse20039DataFeeds {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20039DataFeeds
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataFeeds
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataFeeds
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20039DataFeeds
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20039DataFeeds
     */
    isExplicit?: InlineResponse20039DataFeedsIsExplicitEnum;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataFeeds
     */
    scheduledPost?: string;
    /**
     * 
     * @type {UserLiteModel}
     * @memberof InlineResponse20039DataFeeds
     */
    users?: UserLiteModel;
    /**
     * 
     * @type {InlineResponse20039DataArtworkShareInfo}
     * @memberof InlineResponse20039DataFeeds
     */
    artworkShareInfo?: InlineResponse20039DataArtworkShareInfo;
    /**
     * 
     * @type {Array<ArtworkAssetsModel>}
     * @memberof InlineResponse20039DataFeeds
     */
    artworkAssets?: Array<ArtworkAssetsModel>;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20039DataFeeds
     */
    liked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20039DataFeeds
     */
    saved?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataFeeds
     */
    visibility?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataFeeds
     */
    whoCanReply?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataFeeds
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataFeeds
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20039DataFeeds
     */
    type?: InlineResponse20039DataFeedsTypeEnum;
    /**
     * 
     * @type {InlineResponse20039DataCount}
     * @memberof InlineResponse20039DataFeeds
     */
    count?: InlineResponse20039DataCount;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse20039DataFeedsIsExplicitEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
    * @export
    * @enum {string}
    */
export enum InlineResponse20039DataFeedsTypeEnum {
    Artwork = 'artwork',
    Feed = 'feed'
}

