/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20030DataUserLiked } from './inline-response20030-data-user-liked';
import { InlineResponse20033DataArtworks } from './inline-response20033-data-artworks';
/**
 * 
 * @export
 * @interface InlineResponse20034DataNotifications
 */
export interface InlineResponse20034DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20034DataNotifications
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20034DataNotifications
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20034DataNotifications
     */
    commentId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20034DataNotifications
     */
    comment?: string;
    /**
     * 
     * @type {Array<InlineResponse20030DataUserLiked>}
     * @memberof InlineResponse20034DataNotifications
     */
    userReplied?: Array<InlineResponse20030DataUserLiked>;
    /**
     * 
     * @type {InlineResponse20033DataArtworks}
     * @memberof InlineResponse20034DataNotifications
     */
    artworks?: InlineResponse20033DataArtworks;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20034DataNotifications
     */
    totalLiked?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20034DataNotifications
     */
    restTotalLiked?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20034DataNotifications
     */
    createdAt?: string;
}
