/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaginationModel } from './pagination-model';
import { ReplyModel } from './reply-model';
/**
 * 
 * @export
 * @interface InlineResponse20019Data
 */
export interface InlineResponse20019Data {
    /**
     * 
     * @type {Array<ReplyModel & any>}
     * @memberof InlineResponse20019Data
     */
    replies?: Array<ReplyModel & any>;
    /**
     * 
     * @type {PaginationModel}
     * @memberof InlineResponse20019Data
     */
    pagination?: PaginationModel;
}
