/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20041Feed } from './inline-response20041-feed';
/**
 * 
 * @export
 * @interface InlineResponse20041
 */
export interface InlineResponse20041 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20041
     */
    success?: boolean;
    /**
     * 
     * @type {InlineResponse20041Feed}
     * @memberof InlineResponse20041
     */
    feed?: InlineResponse20041Feed;
}
