/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20030DataArtworks } from './inline-response20030-data-artworks';
import { InlineResponse20030DataUsers } from './inline-response20030-data-users';
/**
 * 
 * @export
 * @interface InlineResponse20030DataNotifications
 */
export interface InlineResponse20030DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030DataNotifications
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030DataNotifications
     */
    workId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20030DataNotifications
     */
    comment?: string;
    /**
     * 
     * @type {InlineResponse20030DataUsers}
     * @memberof InlineResponse20030DataNotifications
     */
    users?: InlineResponse20030DataUsers;
    /**
     * 
     * @type {InlineResponse20030DataArtworks}
     * @memberof InlineResponse20030DataNotifications
     */
    artworks?: InlineResponse20030DataArtworks;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20030DataNotifications
     */
    createdAt?: string;
}
