/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20032DataArtworks } from './inline-response20032-data-artworks';
import { InlineResponse20032DataUserLiked } from './inline-response20032-data-user-liked';
/**
 * 
 * @export
 * @interface InlineResponse20032DataNotifications
 */
export interface InlineResponse20032DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032DataNotifications
     */
    commentId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20032DataNotifications
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032DataNotifications
     */
    isRead?: number;
    /**
     * 
     * @type {Array<InlineResponse20032DataUserLiked>}
     * @memberof InlineResponse20032DataNotifications
     */
    userLiked?: Array<InlineResponse20032DataUserLiked>;
    /**
     * 
     * @type {InlineResponse20032DataArtworks}
     * @memberof InlineResponse20032DataNotifications
     */
    artworks?: InlineResponse20032DataArtworks;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032DataNotifications
     */
    totalLiked?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032DataNotifications
     */
    restTotalLiked?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20032DataNotifications
     */
    createdAt?: string;
}
