/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20031DataArtworksArtworkAssets } from './inline-response20031-data-artworks-artwork-assets';
/**
 * 
 * @export
 * @interface InlineResponse20032DataArtworks
 */
export interface InlineResponse20032DataArtworks {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032DataArtworks
     */
    id?: number;
    /**
     * 
     * @type {InlineResponse20031DataArtworksArtworkAssets}
     * @memberof InlineResponse20032DataArtworks
     */
    assets?: InlineResponse20031DataArtworksArtworkAssets;
}
