/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20021Data } from './inline-response20021-data';
/**
 * 
 * @export
 * @interface InlineResponse20021
 */
export interface InlineResponse20021 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20021
     */
    success?: boolean;
    /**
     * 
     * @type {InlineResponse20021Data}
     * @memberof InlineResponse20021
     */
    data?: InlineResponse20021Data;
}
