/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20015Data
 */
export interface InlineResponse20015Data {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20015Data
     */
    albumId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20015Data
     */
    workId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20015Data
     */
    createdAt?: string;
}
