/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SuccessMessageModel } from './success-message-model';
/**
 * 
 * @export
 * @interface InlineResponse20043
 */
export interface InlineResponse20043 extends SuccessMessageModel {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20043
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20043
     */
    paymentType?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20043
     */
    orderData?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20043
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20043
     */
    until?: string;
}
