/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20014Data } from './inline-response20014-data';
/**
 * 
 * @export
 * @interface InlineResponse20022
 */
export interface InlineResponse20022 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20022
     */
    success?: boolean;
    /**
     * 
     * @type {InlineResponse20014Data}
     * @memberof InlineResponse20022
     */
    data?: InlineResponse20014Data;
}
