/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20030DataUserLiked } from './inline-response20030-data-user-liked';
/**
 * 
 * @export
 * @interface InlineResponse20030DataNotifications
 */
export interface InlineResponse20030DataNotifications {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030DataNotifications
     */
    workId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030DataNotifications
     */
    isRead?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20030DataNotifications
     */
    driver?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20030DataNotifications
     */
    bucket?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20030DataNotifications
     */
    b2FileId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20030DataNotifications
     */
    filename?: string;
    /**
     * 
     * @type {Array<InlineResponse20030DataUserLiked>}
     * @memberof InlineResponse20030DataNotifications
     */
    userLiked?: Array<InlineResponse20030DataUserLiked>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030DataNotifications
     */
    totalLiked?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030DataNotifications
     */
    restTotalLiked?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20030DataNotifications
     */
    createdAt?: string;
}
