/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20040DataFeeds } from './inline-response20040-data-feeds';
import { PaginationModel } from './pagination-model';
/**
 * 
 * @export
 * @interface InlineResponse20040Data
 */
export interface InlineResponse20040Data {
    /**
     * 
     * @type {Array<InlineResponse20040DataFeeds>}
     * @memberof InlineResponse20040Data
     */
    feeds?: Array<InlineResponse20040DataFeeds>;
    /**
     * 
     * @type {PaginationModel}
     * @memberof InlineResponse20040Data
     */
    pagination?: PaginationModel;
}
