/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FeedsUpdateBody
 */
export interface FeedsUpdateBody {
    /**
     * 
     * @type {number}
     * @memberof FeedsUpdateBody
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof FeedsUpdateBody
     */
    text: number;
    /**
     * 
     * @type {string}
     * @memberof FeedsUpdateBody
     */
    visibility: FeedsUpdateBodyVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof FeedsUpdateBody
     */
    whoCanReply: FeedsUpdateBodyWhoCanReplyEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum FeedsUpdateBodyVisibilityEnum {
    Public = 'public',
    Followers = 'followers'
}
/**
    * @export
    * @enum {string}
    */
export enum FeedsUpdateBodyWhoCanReplyEnum {
    Public = 'public',
    Followers = 'followers'
}

