/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20029DataNotifications } from './inline-response20029-data-notifications';
import { PaginationModel } from './pagination-model';
/**
 * 
 * @export
 * @interface InlineResponse20029Data
 */
export interface InlineResponse20029Data {
    /**
     * 
     * @type {Array<InlineResponse20029DataNotifications>}
     * @memberof InlineResponse20029Data
     */
    notifications?: Array<InlineResponse20029DataNotifications>;
    /**
     * 
     * @type {PaginationModel}
     * @memberof InlineResponse20029Data
     */
    pagination?: PaginationModel;
}
