/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20019Data } from './inline-response20019-data';
/**
 * 
 * @export
 * @interface InlineResponse20019
 */
export interface InlineResponse20019 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20019
     */
    success?: boolean;
    /**
     * 
     * @type {InlineResponse20019Data}
     * @memberof InlineResponse20019
     */
    data?: InlineResponse20019Data;
}
