/* tslint:disable */
/* eslint-disable */
/**
 * Upy API Documentation
 * API documentation of Upy - a social community platform for Artists.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserSettingModel
 */
export interface UserSettingModel {
    /**
     * 
     * @type {number}
     * @memberof UserSettingModel
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof UserSettingModel
     */
    darkMode?: number;
    /**
     * 
     * @type {string}
     * @memberof UserSettingModel
     */
    language?: string;
    /**
     * 
     * @type {number}
     * @memberof UserSettingModel
     */
    showExplicit?: number;
}
